version: "3"
services:
    server:
        container_name: reignserver
        restart: always
        build: ./backend
        ports: 
            - "3000:3000"
        links: 
            - mongo
        volumes: 
            - ./backend:/usr/src/app
    frontend:
        container_name: reginfrontend
        restart: always
        build: ./frontend
        ports: 
            - "3001:3000"
        volumes: 
            - ./frontend:/usr/src/app
        tty: true
    mongo:
        container_name: reigndb
        image: mongo
        ports: 
            - "27017:27017"
        logging:
            driver: none
    nginx:
        container_name: nginx
        build: ./nginx
        ports: 
            - "80:80"
        depends_on: 
            - frontend
            - server